//  ****************************
//  * 定义网络请求返回的数据类型
//  * Code By:Dias Software Inc
//  ****************************
class Res {
  int code = 0;
  Object data = {};
  bool success = false;
  Res({code, data, success});
}

class Autogenerated {
  bool? success;
  String? message;
  int? code;

  Autogenerated({this.success, this.message, this.code});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    code = json['code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['message'] = this.message;
    data['code'] = this.code;
    return data;
  }
}
